#!/usr/bin/env python3
"""Convert a vendor vehicle catalogue JSON into a Supabase seed SQL file.

Supported generic shapes:

1) AutoDB-like:
{
  "brands": [
    {
      "name": "BMW",
      "country": "Germany",
      "models": [
        {"name": "3 Series", "type": "Sedan", "years": "1975-present"}
      ]
    }
  ]
}

2) Simple:
[
  {"make": "BMW", "models": ["1 Series", "3 Series"]}
]
"""

from __future__ import annotations

import argparse
import json
import re
from pathlib import Path
from typing import Any


ROOT = Path(__file__).resolve().parents[1]
DEFAULT_OUTPUT = ROOT / "supabase" / "seeds" / "vehicle_catalog_from_vendor.sql"


def slugify(value: str) -> str:
    value = value.strip().lower()
    value = re.sub(r"[^a-z0-9]+", "-", value)
    return re.sub(r"-+", "-", value).strip("-")


def sql_quote(value: str | None) -> str:
    if value is None:
        return "null"

    return "'" + value.replace("'", "''") + "'"


def load_catalog(input_path: Path) -> list[dict[str, Any]]:
    payload = json.loads(input_path.read_text())

    if isinstance(payload, dict):
        raw_brands = payload.get("brands") or payload.get("makes") or []
    elif isinstance(payload, list):
        raw_brands = payload
    else:
        raise ValueError("Unsupported JSON catalogue shape")

    brands = []
    for raw_brand in raw_brands:
        make_name = raw_brand.get("name") or raw_brand.get("make")
        if not make_name:
            continue

        models = []
        for raw_model in raw_brand.get("models", []):
            if isinstance(raw_model, str):
                model_name = raw_model
                vehicle_type = "car"
                year_from = None
                year_to = None
            else:
                model_name = raw_model.get("name") or raw_model.get("model")
                vehicle_type = normalize_vehicle_type(
                    raw_model.get("vehicle_type") or raw_model.get("type")
                )
                year_from, year_to = parse_years(raw_model.get("years"))

            if not model_name:
                continue

            models.append(
                {
                    "name": clean_name(model_name),
                    "slug": slugify(model_name),
                    "vehicle_type": vehicle_type,
                    "year_from": year_from,
                    "year_to": year_to,
                }
            )

        brands.append(
            {
                "name": clean_name(make_name),
                "slug": slugify(make_name),
                "country_code": country_to_code(raw_brand.get("country")),
                "models": models,
            }
        )

    return sorted(brands, key=lambda brand: brand["name"])


def clean_name(value: str) -> str:
    return re.sub(r"\s+", " ", value).strip()


def normalize_vehicle_type(value: str | None) -> str:
    if not value:
        return "car"

    normalized = value.lower()

    if "motor" in normalized:
        return "motorcycle"
    if "truck" in normalized:
        return "truck"
    if "van" in normalized:
        return "van"
    if "camper" in normalized or "motorhome" in normalized:
        return "camper"

    return "car"


def parse_years(value: str | None) -> tuple[int | None, int | None]:
    if not value:
        return None, None

    numbers = [int(match) for match in re.findall(r"\b(19\d{2}|20\d{2})\b", value)]

    if not numbers:
        return None, None

    year_from = min(numbers)
    year_to = None if "present" in value.lower() else max(numbers)

    return year_from, year_to


def country_to_code(country: str | None) -> str | None:
    if not country:
        return None

    lookup = {
        "france": "FR",
        "germany": "DE",
        "italy": "IT",
        "japan": "JP",
        "spain": "ES",
        "south korea": "KR",
        "sweden": "SE",
        "united kingdom": "GB",
        "united states": "US",
    }

    return lookup.get(country.strip().lower())


def write_sql(brands: list[dict[str, Any]], output_path: Path, source_code: str) -> None:
    output_path.parent.mkdir(parents=True, exist_ok=True)
    lines = [
        "-- Generated by scripts/import_vehicle_catalog_json.py",
        f"-- Source: {source_code}",
        "begin;",
        "",
    ]

    for display_order, brand in enumerate(brands, start=1):
        lines.extend(
            [
                "with upserted_make as (",
                "  insert into public.vehicle_makes",
                "    (name, slug, country_code, source_code, external_id, market_regions, display_order, active)",
                "  values",
                f"    ({sql_quote(brand['name'])}, {sql_quote(brand['slug'])}, {sql_quote(brand['country_code'])}, {sql_quote(source_code)}, {sql_quote(brand['slug'])}, array['EU','ES']::text[], {display_order}, true)",
                "  on conflict (source_code, external_id) do update",
                "  set name = excluded.name,",
                "      slug = excluded.slug,",
                "      country_code = excluded.country_code,",
                "      market_regions = excluded.market_regions,",
                "      display_order = excluded.display_order,",
                "      active = true,",
                "      updated_at = now()",
                "  returning id",
                ")",
                "insert into public.vehicle_models",
                "  (make_id, name, slug, vehicle_type, source_code, external_id, market_regions, year_from, year_to, active)",
                "values",
            ]
        )

        values = []
        for model in brand["models"]:
            external_id = f"{brand['slug']}:{model['slug']}"
            values.append(
                "  ("
                "(select id from upserted_make), "
                f"{sql_quote(model['name'])}, "
                f"{sql_quote(model['slug'])}, "
                f"{sql_quote(model['vehicle_type'])}, "
                f"{sql_quote(source_code)}, "
                f"{sql_quote(external_id)}, "
                "array['EU','ES']::text[], "
                f"{model['year_from'] if model['year_from'] else 'null'}, "
                f"{model['year_to'] if model['year_to'] else 'null'}, "
                "true"
                ")"
            )

        if values:
            lines.append(",\n".join(values))
            lines.extend(
                [
                    "on conflict (source_code, external_id) do update",
                    "set make_id = excluded.make_id,",
                    "    name = excluded.name,",
                    "    slug = excluded.slug,",
                    "    vehicle_type = excluded.vehicle_type,",
                    "    market_regions = excluded.market_regions,",
                    "    year_from = excluded.year_from,",
                    "    year_to = excluded.year_to,",
                    "    active = true,",
                    "    updated_at = now();",
                    "",
                ]
            )
        else:
            lines.extend(["select null where false;", ""])

    lines.extend(["commit;", ""])
    output_path.write_text("\n".join(lines))


def main() -> None:
    parser = argparse.ArgumentParser()
    parser.add_argument("input", type=Path)
    parser.add_argument("--output", type=Path, default=DEFAULT_OUTPUT)
    parser.add_argument("--source-code", default="vendor_eu_catalog")
    args = parser.parse_args()

    brands = load_catalog(args.input)
    write_sql(brands, args.output, args.source_code)

    models_count = sum(len(brand["models"]) for brand in brands)
    print(f"Wrote {len(brands)} makes and {models_count} models")
    print(args.output)


if __name__ == "__main__":
    main()
