-- Initial schema for the workshop discovery platform.
-- Target: Supabase Postgres with PostGIS.

create schema if not exists extensions;

create extension if not exists postgis with schema extensions;
create extension if not exists pg_trgm with schema extensions;
create extension if not exists unaccent with schema extensions;
create extension if not exists pgcrypto with schema extensions;

set search_path = public, extensions;

-- Shared timestamp helper.
create or replace function public.set_updated_at()
returns trigger
language plpgsql
as $$
begin
  new.updated_at = now();
  return new;
end;
$$;

-- User profiles mirror auth.users and keep app roles out of auth metadata.
create table public.profiles (
  id uuid primary key references auth.users(id) on delete cascade,
  role text not null default 'customer'
    check (role in ('customer', 'workshop_owner', 'moderator', 'admin')),
  full_name text,
  avatar_url text,
  preferred_locale text not null default 'ca'
    check (preferred_locale in ('ca', 'es', 'en')),
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create trigger profiles_set_updated_at
before update on public.profiles
for each row execute function public.set_updated_at();

create or replace function public.handle_new_user()
returns trigger
language plpgsql
security definer
set search_path = public
as $$
begin
  insert into public.profiles (id, full_name, avatar_url)
  values (
    new.id,
    coalesce(new.raw_user_meta_data->>'full_name', new.raw_user_meta_data->>'name'),
    new.raw_user_meta_data->>'avatar_url'
  )
  on conflict (id) do nothing;

  return new;
end;
$$;

create trigger on_auth_user_created
after insert on auth.users
for each row execute function public.handle_new_user();

create or replace function public.is_admin()
returns boolean
language sql
stable
security definer
set search_path = public
as $$
  select exists (
    select 1
    from public.profiles
    where id = auth.uid()
      and role in ('admin', 'moderator')
  );
$$;

-- Vehicle catalogue.
create table public.vehicle_makes (
  id bigint generated by default as identity primary key,
  name text not null unique,
  slug text not null unique,
  country_code char(2),
  active boolean not null default true,
  created_at timestamptz not null default now()
);

create table public.vehicle_models (
  id bigint generated by default as identity primary key,
  make_id bigint not null references public.vehicle_makes(id) on delete cascade,
  name text not null,
  slug text not null,
  vehicle_type text not null default 'car'
    check (vehicle_type in ('car', 'van', 'motorcycle', 'truck', 'camper', 'other')),
  active boolean not null default true,
  created_at timestamptz not null default now(),
  unique (make_id, slug)
);

create index vehicle_models_make_id_idx on public.vehicle_models(make_id);

create table public.user_vehicles (
  id uuid primary key default extensions.gen_random_uuid(),
  user_id uuid not null references public.profiles(id) on delete cascade,
  make_id bigint not null references public.vehicle_makes(id),
  model_id bigint references public.vehicle_models(id),
  nickname text,
  year smallint check (year between 1950 and 2100),
  fuel_type text check (
    fuel_type in ('gasoline', 'diesel', 'hybrid', 'plug_in_hybrid', 'electric', 'lpg', 'cng', 'hydrogen', 'other')
  ),
  engine text,
  trim text,
  odometer_km integer check (odometer_km is null or odometer_km >= 0),
  license_plate_hash text,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create index user_vehicles_user_id_idx on public.user_vehicles(user_id);

create trigger user_vehicles_set_updated_at
before update on public.user_vehicles
for each row execute function public.set_updated_at();

-- Import and attribution layer.
create table public.data_sources (
  id bigint generated by default as identity primary key,
  code text not null unique,
  name text not null,
  source_type text not null
    check (source_type in ('official_registry', 'open_data', 'osm', 'dgt', 'owner', 'user', 'manual')),
  country_code char(2) not null default 'ES',
  license_name text,
  license_url text,
  attribution_required boolean not null default true,
  url text,
  active boolean not null default true,
  created_at timestamptz not null default now()
);

insert into public.data_sources
  (code, name, source_type, license_name, license_url, url)
values
  ('osm', 'OpenStreetMap', 'osm', 'ODbL', 'https://www.openstreetmap.org/copyright', 'https://www.openstreetmap.org'),
  ('dgt_libro_taller', 'DGT Libro Taller', 'dgt', null, null, 'https://www.dgt.es/conoce-la-dgt/con-quien-trabajamos/talleres/'),
  ('datos_gob_es', 'datos.gob.es', 'open_data', null, null, 'https://datos.gob.es'),
  ('cat_rasic', 'Catalunya RASIC - Tallers de reparacio de vehicles', 'official_registry', null, null, 'https://datos.gob.es/es/catalogo/a09002970-talleres-de-reparacion-de-vehiculos'),
  ('jcyl_workshops', 'Castilla y Leon - Talleres de reparacion de vehiculos', 'official_registry', null, null, 'https://datos.gob.es'),
  ('xunta_workshops', 'Xunta de Galicia - Registro de talleres de reparacion de vehiculos', 'official_registry', null, null, 'https://datos.gob.es'),
  ('owner_claim', 'Workshop owner supplied data', 'owner', null, null, null)
on conflict (code) do nothing;

create table public.raw_workshop_imports (
  id uuid primary key default extensions.gen_random_uuid(),
  source_id bigint not null references public.data_sources(id),
  external_id text,
  raw_payload jsonb not null,
  normalized_payload jsonb,
  import_status text not null default 'pending'
    check (import_status in ('pending', 'processed', 'duplicate', 'rejected', 'error')),
  error_message text,
  matched_workshop_id uuid,
  imported_at timestamptz not null default now(),
  processed_at timestamptz
);

create index raw_workshop_imports_source_external_idx
  on public.raw_workshop_imports(source_id, external_id);

create index raw_workshop_imports_payload_gin_idx
  on public.raw_workshop_imports using gin(raw_payload);

-- Workshop master data.
create table public.workshops (
  id uuid primary key default extensions.gen_random_uuid(),
  name text not null,
  slug text not null unique,
  legal_name text,
  description text,
  status text not null default 'published'
    check (status in ('draft', 'published', 'closed', 'duplicate', 'hidden')),
  claimed_by_user_id uuid references public.profiles(id) on delete set null,
  verified boolean not null default false,
  dgt_libro_taller boolean not null default false,
  country_code char(2) not null default 'ES',
  autonomous_community text,
  province text,
  municipality text,
  postal_code text,
  address_line text,
  location extensions.geography(Point, 4326) not null,
  phone text,
  email text,
  website text,
  hourly_rate_eur numeric(7,2) check (hourly_rate_eur is null or hourly_rate_eur >= 0),
  min_quote_eur numeric(8,2) check (min_quote_eur is null or min_quote_eur >= 0),
  currency char(3) not null default 'EUR',
  opening_hours jsonb not null default '{}'::jsonb,
  source_confidence numeric(4,2) not null default 0.50
    check (source_confidence between 0 and 1),
  data_quality_status text not null default 'unverified'
    check (data_quality_status in ('unverified', 'imported', 'owner_verified', 'admin_verified', 'needs_review')),
  duplicate_of uuid references public.workshops(id),
  raw_attributes jsonb not null default '{}'::jsonb,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create index workshops_location_gist_idx on public.workshops using gist(location);
create index workshops_status_idx on public.workshops(status);
create index workshops_geo_admin_idx on public.workshops(country_code, autonomous_community, province, municipality);
create index workshops_name_trgm_idx on public.workshops using gin(name gin_trgm_ops);
create index workshops_raw_attributes_gin_idx on public.workshops using gin(raw_attributes);

create trigger workshops_set_updated_at
before update on public.workshops
for each row execute function public.set_updated_at();

alter table public.raw_workshop_imports
add constraint raw_workshop_imports_matched_workshop_fk
foreign key (matched_workshop_id) references public.workshops(id) on delete set null;

create table public.workshop_external_ids (
  workshop_id uuid not null references public.workshops(id) on delete cascade,
  source_id bigint not null references public.data_sources(id),
  external_id text not null,
  raw_url text,
  last_seen_at timestamptz not null default now(),
  primary key (source_id, external_id)
);

create index workshop_external_ids_workshop_id_idx
  on public.workshop_external_ids(workshop_id);

-- Services, features and matching metadata.
create table public.service_categories (
  id bigint generated by default as identity primary key,
  code text not null unique,
  name_ca text not null,
  name_es text not null,
  parent_id bigint references public.service_categories(id),
  active boolean not null default true
);

insert into public.service_categories (code, name_ca, name_es) values
  ('diagnostics', 'Diagnosi', 'Diagnosis'),
  ('maintenance', 'Manteniment', 'Mantenimiento'),
  ('mechanical_repair', 'Reparacio mecanica', 'Reparacion mecanica'),
  ('bodywork_paint', 'Planxa i pintura', 'Chapa y pintura'),
  ('tyres', 'Pneumatics', 'Neumaticos'),
  ('brakes', 'Frens', 'Frenos'),
  ('air_conditioning', 'Aire condicionat', 'Aire acondicionado'),
  ('electric_hybrid', 'Electric i hybrid', 'Electrico e hibrido'),
  ('glass', 'Llunes', 'Lunas'),
  ('itv_prep', 'Pre-ITV', 'Pre-ITV'),
  ('transmission', 'Transmissio', 'Transmision'),
  ('roadside_assistance', 'Assistencia en carretera', 'Asistencia en carretera'),
  ('fleet', 'Flotes', 'Flotas')
on conflict (code) do nothing;

create table public.workshop_services (
  workshop_id uuid not null references public.workshops(id) on delete cascade,
  service_category_id bigint not null references public.service_categories(id),
  price_from_eur numeric(8,2) check (price_from_eur is null or price_from_eur >= 0),
  notes text,
  primary key (workshop_id, service_category_id)
);

create index workshop_services_service_idx on public.workshop_services(service_category_id);

create table public.workshop_features (
  workshop_id uuid not null references public.workshops(id) on delete cascade,
  feature_code text not null check (
    feature_code in (
      'courtesy_car',
      'pickup_delivery',
      'tow_truck',
      'financing',
      'insurance_network',
      'online_booking',
      'same_day_service',
      'warranty',
      'wheelchair_accessible'
    )
  ),
  details jsonb not null default '{}'::jsonb,
  primary key (workshop_id, feature_code)
);

create table public.workshop_vehicle_types (
  workshop_id uuid not null references public.workshops(id) on delete cascade,
  vehicle_type text not null
    check (vehicle_type in ('car', 'van', 'motorcycle', 'truck', 'camper', 'other')),
  primary key (workshop_id, vehicle_type)
);

create table public.workshop_brand_specializations (
  workshop_id uuid not null references public.workshops(id) on delete cascade,
  make_id bigint not null references public.vehicle_makes(id),
  level text not null default 'accepted'
    check (level in ('official', 'specialist', 'frequent', 'accepted')),
  notes text,
  primary key (workshop_id, make_id)
);

create index workshop_brand_specializations_make_idx
  on public.workshop_brand_specializations(make_id, level);

-- Claims let owners take control of imported workshop records.
create table public.workshop_claims (
  id uuid primary key default extensions.gen_random_uuid(),
  workshop_id uuid not null references public.workshops(id) on delete cascade,
  user_id uuid not null references public.profiles(id) on delete cascade,
  status text not null default 'pending'
    check (status in ('pending', 'approved', 'rejected', 'cancelled')),
  evidence jsonb not null default '{}'::jsonb,
  reviewed_by uuid references public.profiles(id),
  reviewed_at timestamptz,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  unique (workshop_id, user_id)
);

create index workshop_claims_user_id_idx on public.workshop_claims(user_id);
create index workshop_claims_workshop_id_idx on public.workshop_claims(workshop_id);

create trigger workshop_claims_set_updated_at
before update on public.workshop_claims
for each row execute function public.set_updated_at();

-- Reviews use 0-10 scores, matching the product brief.
create table public.reviews (
  id uuid primary key default extensions.gen_random_uuid(),
  workshop_id uuid not null references public.workshops(id) on delete cascade,
  user_id uuid not null references public.profiles(id) on delete cascade,
  user_vehicle_id uuid references public.user_vehicles(id) on delete set null,
  service_category_id bigint references public.service_categories(id),
  service_date date,
  score_service smallint not null check (score_service between 0 and 10),
  score_treatment smallint not null check (score_treatment between 0 and 10),
  score_knowledge smallint not null check (score_knowledge between 0 and 10),
  score_price_value smallint not null check (score_price_value between 0 and 10),
  score_would_return smallint not null check (score_would_return between 0 and 10),
  overall_score numeric(4,2) generated always as (
    (
      score_service +
      score_treatment +
      score_knowledge +
      score_price_value +
      score_would_return
    ) / 5.0
  ) stored,
  comment text,
  verified_visit boolean not null default false,
  status text not null default 'published'
    check (status in ('pending', 'published', 'hidden', 'rejected')),
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create index reviews_workshop_status_created_idx
  on public.reviews(workshop_id, status, created_at desc);

create index reviews_user_id_idx on public.reviews(user_id);
create index reviews_user_vehicle_id_idx on public.reviews(user_vehicle_id);

create trigger reviews_set_updated_at
before update on public.reviews
for each row execute function public.set_updated_at();

create table public.review_reports (
  id uuid primary key default extensions.gen_random_uuid(),
  review_id uuid not null references public.reviews(id) on delete cascade,
  user_id uuid not null references public.profiles(id) on delete cascade,
  reason text not null check (reason in ('spam', 'abuse', 'fake', 'privacy', 'other')),
  details text,
  status text not null default 'pending'
    check (status in ('pending', 'reviewed', 'dismissed')),
  created_at timestamptz not null default now(),
  unique (review_id, user_id)
);

create table public.workshop_review_stats (
  workshop_id uuid primary key references public.workshops(id) on delete cascade,
  review_count integer not null default 0,
  verified_review_count integer not null default 0,
  avg_service numeric(4,2),
  avg_treatment numeric(4,2),
  avg_knowledge numeric(4,2),
  avg_price_value numeric(4,2),
  avg_would_return numeric(4,2),
  avg_overall_score numeric(4,2),
  bayesian_score numeric(4,2),
  updated_at timestamptz not null default now()
);

create or replace function public.refresh_workshop_review_stats(p_workshop_id uuid)
returns void
language plpgsql
security definer
set search_path = public, extensions
as $$
declare
  prior_avg constant numeric := 7.00;
  prior_weight constant numeric := 5.00;
begin
  insert into public.workshop_review_stats (
    workshop_id,
    review_count,
    verified_review_count,
    avg_service,
    avg_treatment,
    avg_knowledge,
    avg_price_value,
    avg_would_return,
    avg_overall_score,
    bayesian_score,
    updated_at
  )
  select
    p_workshop_id,
    count(*)::integer,
    count(*) filter (where verified_visit)::integer,
    round(avg(score_service)::numeric, 2),
    round(avg(score_treatment)::numeric, 2),
    round(avg(score_knowledge)::numeric, 2),
    round(avg(score_price_value)::numeric, 2),
    round(avg(score_would_return)::numeric, 2),
    round(avg(overall_score)::numeric, 2),
    case
      when count(*) = 0 then null
      else round(((avg(overall_score) * count(*)) + (prior_avg * prior_weight)) / (count(*) + prior_weight), 2)
    end,
    now()
  from public.reviews
  where workshop_id = p_workshop_id
    and status = 'published'
  on conflict (workshop_id) do update
  set
    review_count = excluded.review_count,
    verified_review_count = excluded.verified_review_count,
    avg_service = excluded.avg_service,
    avg_treatment = excluded.avg_treatment,
    avg_knowledge = excluded.avg_knowledge,
    avg_price_value = excluded.avg_price_value,
    avg_would_return = excluded.avg_would_return,
    avg_overall_score = excluded.avg_overall_score,
    bayesian_score = excluded.bayesian_score,
    updated_at = now();
end;
$$;

create or replace function public.reviews_refresh_workshop_stats()
returns trigger
language plpgsql
security definer
set search_path = public, extensions
as $$
begin
  if tg_op in ('UPDATE', 'DELETE') then
    perform public.refresh_workshop_review_stats(old.workshop_id);
  end if;

  if tg_op in ('INSERT', 'UPDATE') then
    perform public.refresh_workshop_review_stats(new.workshop_id);
  end if;

  return null;
end;
$$;

create trigger reviews_refresh_workshop_stats_trigger
after insert or update or delete on public.reviews
for each row execute function public.reviews_refresh_workshop_stats();

-- Public RPC for map/list search. RLS still applies to the underlying tables.
create or replace function public.search_workshops(
  p_lat double precision,
  p_lng double precision,
  p_radius_m integer default 25000,
  p_make_id bigint default null,
  p_service_code text default null,
  p_max_hourly_rate_eur numeric default null,
  p_min_bayesian_score numeric default null,
  p_limit integer default 50,
  p_offset integer default 0
)
returns table (
  id uuid,
  name text,
  slug text,
  address_line text,
  municipality text,
  province text,
  latitude double precision,
  longitude double precision,
  distance_m double precision,
  hourly_rate_eur numeric,
  verified boolean,
  dgt_libro_taller boolean,
  review_count integer,
  avg_overall_score numeric,
  bayesian_score numeric,
  brand_match boolean
)
language sql
stable
as $$
  with query_point as (
    select extensions.st_setsrid(extensions.st_makepoint(p_lng, p_lat), 4326)::extensions.geography as location
  )
  select
    w.id,
    w.name,
    w.slug,
    w.address_line,
    w.municipality,
    w.province,
    extensions.st_y(w.location::extensions.geometry) as latitude,
    extensions.st_x(w.location::extensions.geometry) as longitude,
    extensions.st_distance(w.location, qp.location) as distance_m,
    w.hourly_rate_eur,
    w.verified,
    w.dgt_libro_taller,
    coalesce(s.review_count, 0) as review_count,
    s.avg_overall_score,
    s.bayesian_score,
    exists (
      select 1
      from public.workshop_brand_specializations wbs
      where wbs.workshop_id = w.id
        and wbs.make_id = p_make_id
    ) as brand_match
  from public.workshops w
  cross join query_point qp
  left join public.workshop_review_stats s on s.workshop_id = w.id
  where w.status = 'published'
    and extensions.st_dwithin(
      w.location,
      qp.location,
      least(greatest(coalesce(p_radius_m, 25000), 100), 200000)
    )
    and (
      p_make_id is null
      or exists (
        select 1
        from public.workshop_brand_specializations wbs
        where wbs.workshop_id = w.id
          and wbs.make_id = p_make_id
      )
    )
    and (
      p_service_code is null
      or exists (
        select 1
        from public.workshop_services ws
        join public.service_categories sc on sc.id = ws.service_category_id
        where ws.workshop_id = w.id
          and sc.code = p_service_code
      )
    )
    and (p_max_hourly_rate_eur is null or w.hourly_rate_eur <= p_max_hourly_rate_eur)
    and (p_min_bayesian_score is null or s.bayesian_score >= p_min_bayesian_score)
  order by
    exists (
      select 1
      from public.workshop_brand_specializations wbs
      where wbs.workshop_id = w.id
        and wbs.make_id = p_make_id
    ) desc,
    coalesce(s.bayesian_score, 0) desc,
    coalesce(s.verified_review_count, 0) desc,
    extensions.st_distance(w.location, qp.location) asc
  limit least(greatest(coalesce(p_limit, 50), 1), 100)
  offset greatest(coalesce(p_offset, 0), 0);
$$;

create or replace function public.workshops_in_view(
  p_min_lat double precision,
  p_min_lng double precision,
  p_max_lat double precision,
  p_max_lng double precision
)
returns table (
  id uuid,
  name text,
  slug text,
  latitude double precision,
  longitude double precision,
  bayesian_score numeric,
  review_count integer
)
language sql
stable
as $$
  select
    w.id,
    w.name,
    w.slug,
    extensions.st_y(w.location::extensions.geometry) as latitude,
    extensions.st_x(w.location::extensions.geometry) as longitude,
    s.bayesian_score,
    coalesce(s.review_count, 0) as review_count
  from public.workshops w
  left join public.workshop_review_stats s on s.workshop_id = w.id
  where w.status = 'published'
    and w.location::extensions.geometry && extensions.st_makeenvelope(
      p_min_lng,
      p_min_lat,
      p_max_lng,
      p_max_lat,
      4326
    );
$$;

-- Row level security.
alter table public.profiles enable row level security;
alter table public.vehicle_makes enable row level security;
alter table public.vehicle_models enable row level security;
alter table public.user_vehicles enable row level security;
alter table public.data_sources enable row level security;
alter table public.raw_workshop_imports enable row level security;
alter table public.workshops enable row level security;
alter table public.workshop_external_ids enable row level security;
alter table public.service_categories enable row level security;
alter table public.workshop_services enable row level security;
alter table public.workshop_features enable row level security;
alter table public.workshop_vehicle_types enable row level security;
alter table public.workshop_brand_specializations enable row level security;
alter table public.workshop_claims enable row level security;
alter table public.reviews enable row level security;
alter table public.review_reports enable row level security;
alter table public.workshop_review_stats enable row level security;

create policy "Users can read their own profile"
on public.profiles for select
using (id = auth.uid() or public.is_admin());

create policy "Users can update their own profile"
on public.profiles for update
using (id = auth.uid())
with check (id = auth.uid());

create policy "Vehicle makes are public"
on public.vehicle_makes for select
using (active = true);

create policy "Admins manage vehicle makes"
on public.vehicle_makes for all
using (public.is_admin())
with check (public.is_admin());

create policy "Vehicle models are public"
on public.vehicle_models for select
using (active = true);

create policy "Admins manage vehicle models"
on public.vehicle_models for all
using (public.is_admin())
with check (public.is_admin());

create policy "Users manage their vehicles"
on public.user_vehicles for all
using (user_id = auth.uid())
with check (user_id = auth.uid());

create policy "Data sources are public"
on public.data_sources for select
using (true);

create policy "Admins manage data sources"
on public.data_sources for all
using (public.is_admin())
with check (public.is_admin());

create policy "Admins manage raw imports"
on public.raw_workshop_imports for all
using (public.is_admin())
with check (public.is_admin());

create policy "Published workshops are public"
on public.workshops for select
using (status = 'published' or claimed_by_user_id = auth.uid() or public.is_admin());

create policy "Owners can create draft workshops"
on public.workshops for insert
with check (claimed_by_user_id = auth.uid() and status in ('draft', 'published'));

create policy "Owners can update claimed workshops"
on public.workshops for update
using (claimed_by_user_id = auth.uid() or public.is_admin())
with check (
  public.is_admin()
  or (
    claimed_by_user_id = auth.uid()
    and status in ('draft', 'published', 'closed')
  )
);

create policy "Workshop external IDs are public"
on public.workshop_external_ids for select
using (
  exists (
    select 1 from public.workshops w
    where w.id = workshop_id
      and w.status = 'published'
  )
  or public.is_admin()
);

create policy "Admins manage workshop external IDs"
on public.workshop_external_ids for all
using (public.is_admin())
with check (public.is_admin());

create policy "Services are public"
on public.service_categories for select
using (active = true);

create policy "Admins manage services"
on public.service_categories for all
using (public.is_admin())
with check (public.is_admin());

create policy "Workshop service mappings are public"
on public.workshop_services for select
using (
  exists (
    select 1 from public.workshops w
    where w.id = workshop_id
      and w.status = 'published'
  )
);

create policy "Owners manage workshop services"
on public.workshop_services for all
using (
  public.is_admin()
  or exists (
    select 1 from public.workshops w
    where w.id = workshop_id
      and w.claimed_by_user_id = auth.uid()
  )
)
with check (
  public.is_admin()
  or exists (
    select 1 from public.workshops w
    where w.id = workshop_id
      and w.claimed_by_user_id = auth.uid()
  )
);

create policy "Workshop features are public"
on public.workshop_features for select
using (
  exists (
    select 1 from public.workshops w
    where w.id = workshop_id
      and w.status = 'published'
  )
);

create policy "Owners manage workshop features"
on public.workshop_features for all
using (
  public.is_admin()
  or exists (
    select 1 from public.workshops w
    where w.id = workshop_id
      and w.claimed_by_user_id = auth.uid()
  )
)
with check (
  public.is_admin()
  or exists (
    select 1 from public.workshops w
    where w.id = workshop_id
      and w.claimed_by_user_id = auth.uid()
  )
);

create policy "Workshop vehicle types are public"
on public.workshop_vehicle_types for select
using (
  exists (
    select 1 from public.workshops w
    where w.id = workshop_id
      and w.status = 'published'
  )
);

create policy "Owners manage workshop vehicle types"
on public.workshop_vehicle_types for all
using (
  public.is_admin()
  or exists (
    select 1 from public.workshops w
    where w.id = workshop_id
      and w.claimed_by_user_id = auth.uid()
  )
)
with check (
  public.is_admin()
  or exists (
    select 1 from public.workshops w
    where w.id = workshop_id
      and w.claimed_by_user_id = auth.uid()
  )
);

create policy "Workshop brand specializations are public"
on public.workshop_brand_specializations for select
using (
  exists (
    select 1 from public.workshops w
    where w.id = workshop_id
      and w.status = 'published'
  )
);

create policy "Owners manage workshop brand specializations"
on public.workshop_brand_specializations for all
using (
  public.is_admin()
  or exists (
    select 1 from public.workshops w
    where w.id = workshop_id
      and w.claimed_by_user_id = auth.uid()
  )
)
with check (
  public.is_admin()
  or exists (
    select 1 from public.workshops w
    where w.id = workshop_id
      and w.claimed_by_user_id = auth.uid()
  )
);

create policy "Users read their own claims"
on public.workshop_claims for select
using (user_id = auth.uid() or public.is_admin());

create policy "Users create their own claims"
on public.workshop_claims for insert
with check (
  user_id = auth.uid()
  and status = 'pending'
  and reviewed_by is null
  and reviewed_at is null
);

create policy "Users cancel their own pending claims"
on public.workshop_claims for update
using (user_id = auth.uid() and status = 'pending')
with check (
  user_id = auth.uid()
  and status in ('pending', 'cancelled')
  and reviewed_by is null
  and reviewed_at is null
);

create policy "Admins manage workshop claims"
on public.workshop_claims for all
using (public.is_admin())
with check (public.is_admin());

create policy "Published reviews are public"
on public.reviews for select
using (status = 'published' or user_id = auth.uid() or public.is_admin());

create policy "Users create their own reviews"
on public.reviews for insert
with check (
  user_id = auth.uid()
  and verified_visit = false
  and status in ('pending', 'published')
  and exists (
    select 1 from public.workshops w
    where w.id = workshop_id
      and w.status = 'published'
  )
  and (
    user_vehicle_id is null
    or exists (
      select 1 from public.user_vehicles uv
      where uv.id = user_vehicle_id
        and uv.user_id = auth.uid()
    )
  )
);

create policy "Users update their own reviews"
on public.reviews for update
using (user_id = auth.uid() and verified_visit = false)
with check (
  user_id = auth.uid()
  and verified_visit = false
  and status in ('pending', 'published')
  and (
    user_vehicle_id is null
    or exists (
      select 1 from public.user_vehicles uv
      where uv.id = user_vehicle_id
        and uv.user_id = auth.uid()
    )
  )
);

create policy "Admins manage reviews"
on public.reviews for all
using (public.is_admin())
with check (public.is_admin());

create policy "Users report reviews"
on public.review_reports for insert
with check (
  user_id = auth.uid()
  and status = 'pending'
  and exists (
    select 1 from public.reviews r
    where r.id = review_id
      and r.status = 'published'
  )
);

create policy "Users read their own review reports"
on public.review_reports for select
using (user_id = auth.uid() or public.is_admin());

create policy "Admins manage review reports"
on public.review_reports for all
using (public.is_admin())
with check (public.is_admin());

create policy "Review stats are public"
on public.workshop_review_stats for select
using (true);

grant usage on schema public to anon, authenticated;
grant usage on schema extensions to anon, authenticated;

grant select on
  public.vehicle_makes,
  public.vehicle_models,
  public.data_sources,
  public.workshops,
  public.workshop_external_ids,
  public.service_categories,
  public.workshop_services,
  public.workshop_features,
  public.workshop_vehicle_types,
  public.workshop_brand_specializations,
  public.reviews,
  public.workshop_review_stats
to anon, authenticated;

grant select on public.profiles to authenticated;
grant update (full_name, avatar_url, preferred_locale) on public.profiles to authenticated;
grant select, insert, update, delete on public.user_vehicles to authenticated;
grant insert (
  name,
  slug,
  legal_name,
  description,
  status,
  claimed_by_user_id,
  country_code,
  autonomous_community,
  province,
  municipality,
  postal_code,
  address_line,
  location,
  phone,
  email,
  website,
  hourly_rate_eur,
  min_quote_eur,
  currency,
  opening_hours
) on public.workshops to authenticated;
grant update (
  name,
  slug,
  legal_name,
  description,
  status,
  autonomous_community,
  province,
  municipality,
  postal_code,
  address_line,
  location,
  phone,
  email,
  website,
  hourly_rate_eur,
  min_quote_eur,
  currency,
  opening_hours
) on public.workshops to authenticated;
grant select, insert, update, delete on
  public.workshop_services,
  public.workshop_features,
  public.workshop_vehicle_types,
  public.workshop_brand_specializations
to authenticated;
grant select on public.workshop_claims to authenticated;
grant insert (workshop_id, user_id, evidence) on public.workshop_claims to authenticated;
grant update (status, evidence) on public.workshop_claims to authenticated;
grant insert (
  workshop_id,
  user_id,
  user_vehicle_id,
  service_category_id,
  service_date,
  score_service,
  score_treatment,
  score_knowledge,
  score_price_value,
  score_would_return,
  comment
) on public.reviews to authenticated;
grant update (
  user_vehicle_id,
  service_category_id,
  service_date,
  score_service,
  score_treatment,
  score_knowledge,
  score_price_value,
  score_would_return,
  comment
) on public.reviews to authenticated;
grant select on public.review_reports to authenticated;
grant insert (review_id, user_id, reason, details) on public.review_reports to authenticated;

grant execute on function public.search_workshops(
  double precision,
  double precision,
  integer,
  bigint,
  text,
  numeric,
  numeric,
  integer,
  integer
) to anon, authenticated;

grant execute on function public.workshops_in_view(
  double precision,
  double precision,
  double precision,
  double precision
) to anon, authenticated;
