-- Vehicle catalogue enrichment for external APIs and market filtering.

alter table public.vehicle_makes
add column if not exists source_code text,
add column if not exists external_id text,
add column if not exists market_regions text[] not null default array['ES']::text[],
add column if not exists display_order integer not null default 1000,
add column if not exists updated_at timestamptz not null default now();

alter table public.vehicle_models
add column if not exists source_code text,
add column if not exists external_id text,
add column if not exists market_regions text[] not null default array['ES']::text[],
add column if not exists year_from smallint,
add column if not exists year_to smallint,
add column if not exists updated_at timestamptz not null default now();

create unique index if not exists vehicle_makes_source_external_uidx
on public.vehicle_makes(source_code, external_id)
where source_code is not null and external_id is not null;

create unique index if not exists vehicle_models_source_external_uidx
on public.vehicle_models(source_code, external_id)
where source_code is not null and external_id is not null;

create index if not exists vehicle_makes_market_regions_gin_idx
on public.vehicle_makes using gin(market_regions);

create index if not exists vehicle_models_market_regions_gin_idx
on public.vehicle_models using gin(market_regions);

create trigger vehicle_makes_set_updated_at
before update on public.vehicle_makes
for each row execute function public.set_updated_at();

create trigger vehicle_models_set_updated_at
before update on public.vehicle_models
for each row execute function public.set_updated_at();

create table if not exists public.vehicle_make_aliases (
  id bigint generated by default as identity primary key,
  make_id bigint not null references public.vehicle_makes(id) on delete cascade,
  alias text not null,
  source_code text,
  created_at timestamptz not null default now(),
  unique (make_id, alias)
);

create table if not exists public.vehicle_model_aliases (
  id bigint generated by default as identity primary key,
  model_id bigint not null references public.vehicle_models(id) on delete cascade,
  alias text not null,
  source_code text,
  created_at timestamptz not null default now(),
  unique (model_id, alias)
);

alter table public.vehicle_make_aliases enable row level security;
alter table public.vehicle_model_aliases enable row level security;

create policy "Vehicle make aliases are public"
on public.vehicle_make_aliases for select
using (true);

create policy "Admins manage vehicle make aliases"
on public.vehicle_make_aliases for all
using (public.is_admin())
with check (public.is_admin());

create policy "Vehicle model aliases are public"
on public.vehicle_model_aliases for select
using (true);

create policy "Admins manage vehicle model aliases"
on public.vehicle_model_aliases for all
using (public.is_admin())
with check (public.is_admin());

grant select on public.vehicle_make_aliases, public.vehicle_model_aliases
to anon, authenticated;

insert into public.data_sources
  (code, name, source_type, country_code, license_name, license_url, url)
values
  (
    'nhtsa_vpic',
    'NHTSA vPIC Vehicle API',
    'open_data',
    'US',
    'Public domain / U.S. Government open data',
    'https://www.nhtsa.gov/nhtsa-datasets-and-apis',
    'https://vpic.nhtsa.dot.gov/api/'
  )
on conflict (code) do nothing;
